[package]
name = "clipboard"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
gpui = "*"
objc2 = "0.6.3"
objc2-app-kit = { version = "0.2", features = ["NSPasteboard"] }
objc2-foundation = { version = "0.2", features = ["NSThread", "dispatch"] }
