[package]
name = "clipboard"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
global-hotkey = "0.7"
objc2 = "0.6.3"
objc2-app-kit = { version = "0.3.2", default-features = false, features = [
"NSApplication",
"NSWindow",
"NSResponder",
"NSControl",
"NSView",
"NSPanel",
"NSButton",
"NSColor",
"NSFont",
"NSStatusBar", "NSStatusItem", "NSMenu", "NSMenuItem",
"NSTextView",
"NSTableCellView",
"NSTextField", "NSTextFieldCell",
"NSPasteboard",
"NSWorkspace",
"NSGraphics",
"NSScreen",
"NSTableView", "NSTableColumn", "NSTableHeaderView",
"NSScrollView", "NSClipView", "NSUserInterfaceItemIdentification",
"NSParagraphStyle",
"objc2-quartz-core",
"NSRunningApplication",
"objc2-core-foundation"
] }
objc2-foundation = { version = "0.3.2", default-features = false, features = [
"NSThread",
"bitflags",
"NSArray",
"NSCoder",
"NSDictionary",
"NSEnumerator",
"NSGeometry",
"NSIndexSet",
"NSNotification",
"NSObject",
"NSRange",
"NSSortDescriptor",
"NSString",
"NSURL",
] }
objc2-quartz-core = { version = "0.3.2", default-features = false, features = ["CALayer", "objc2-core-foundation"] }
dispatch2 = { version = "0.3", default-features = false, features = ["alloc", "objc2"] }
